import React from "react";
import { useAuth } from "../context/AuthContext";
import { DEFAULT_MOCK_TESTS } from "../data/mockTestData";
import { 
  Sparkles, 
  Search, 
  TrendingUp, 
  Award, 
  MapPin, 
  Clock, 
  ArrowRight, 
  Activity, 
  ShieldCheck, 
  Zap, 
  Target,
  BrainCircuit,
  MessageSquareCode
} from "lucide-react";
import { motion } from "motion/react";

interface LandingPageProps {
  setScreen: (screen: string) => void;
  setSelectedTestId: (testId: string) => void;
  onOpenAuth: () => void;
}

export default function LandingPage({ setScreen, setSelectedTestId, onOpenAuth }: LandingPageProps) {
  const { user } = useAuth();

  const categories = [
    { 
      id: "UPSC", 
      title: "UPSC Civil Services", 
      desc: "IAS, IPS, IRS, IFS Practice syllabus", 
      stats: "5,400+ Active Students this week", 
      difficulty: "Very Hard",
      color: "from-amber-500/20 to-orange-500/10",
      accent: "text-amber-400"
    },
    { 
      id: "SSC", 
      title: "SSC CGL / CHSL", 
      desc: "Income Tax, Excise inspector tracks", 
      stats: "24,800+ Solved Mocks yesterday", 
      difficulty: "Medium-Hard",
      color: "from-blue-500/20 to-indigo-500/10",
      accent: "text-blue-400"
    },
    { 
      id: "Banking", 
      title: "Banking (IBPS/SBI PO)", 
      desc: "Probationary Officers, Clerk patterns", 
      stats: "15,200+ Recommended tests", 
      difficulty: "Medium",
      color: "from-emerald-500/20 to-teal-500/10",
      accent: "text-emerald-400"
    },
    { 
      id: "Railways", 
      title: "Railways (RRB NTPC)", 
      desc: "CBT 1 & CBT 2 general practice papers", 
      stats: "18,900+ Candidates preparation logs", 
      difficulty: "Easy-Medium",
      color: "from-purple-500/20 to-pink-500/10",
      accent: "text-purple-400"
    }
  ];

  const handleStartExam = (testId: string) => {
    if (!user) {
      onOpenAuth();
    } else {
      setSelectedTestId(testId);
      setScreen("mock-test");
    }
  };

  return (
    <div className="bg-[#0A0A0A] text-[#F5F5F5] min-h-screen relative overflow-hidden selection:bg-[#FF3B3F] selection:text-white font-sans" id="landing-page-screen">
      
      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-24 relative text-center">
        <motion.div 
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="inline-flex items-center gap-1.5 px-4  py-2 bg-[#1A1A1A] border border-[#2A2A2A] rounded-none text-[10px] text-white font-mono uppercase tracking-widest mb-8"
        >
          <Sparkles className="w-3.5 h-3.5 text-[#FF3B3F]" />
          <span>IND-CENTRIC SMART ENGINE V2.4 IS LIVE</span>
        </motion.div>
 
        <motion.h1 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.1 }}
          className="text-4xl sm:text-6xl lg:text-8xl font-black tracking-tighter text-white font-sans max-w-5xl mx-auto leading-none uppercase mb-8"
        >
          India's Smartest Government Exam{" "}
          <span className="text-[#FF3B3F] block mt-2">
            Test & Analytics Platform
          </span>
        </motion.h1>
 
        <motion.p 
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.2 }}
          className="text-slate-400 text-sm sm:text-base max-w-3xl mx-auto font-sans leading-relaxed mb-12"
        >
          Master the UPSC, SSC, Banking, and Railway exams. Get millisecond accuracy trackers, detailed section-by-section scoring comparisons, and actual predicted ranks generated by our high-fidelity student performance engine.
        </motion.p>
 
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-4 max-w-md mx-auto"
        >
          {user ? (
            <button 
              onClick={() => setScreen("dashboard")}
              className="w-full sm:w-auto px-8 py-4 bg-white hover:bg-[#FF3B3F] hover:border-[#FF3B3F] text-black hover:text-white font-bold text-xs uppercase tracking-widest border border-white rounded-none transition-all duration-200 flex items-center justify-center gap-2"
            >
              <span>Go to My Dashboard</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button 
              onClick={onOpenAuth}
              className="w-full sm:w-auto px-8 py-4 bg-white hover:bg-[#FF3B3F] hover:border-[#FF3B3F] text-black hover:text-white font-bold text-xs uppercase tracking-widest border border-white rounded-none transition-all duration-200 flex items-center justify-center gap-2 cursor-pointer"
            >
              <span>Get Started Free</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
          <button 
            onClick={() => setScreen("pricing")}
            className="w-full sm:w-auto px-8 py-4 bg-transparent hover:bg-white text-white hover:text-black font-bold text-xs uppercase tracking-widest border border-[#2A2A2A] hover:border-white rounded-none transition-all duration-200 flex items-center justify-center gap-2"
          >
            Explore PRO Plans
          </button>
        </motion.div>
      </section>
 
      {/* Trust & Stats Section */}
      <section className="bg-[#1A1A1A] border-y border-[#2A2A2A] py-14 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            <div className="border-r border-[#2A2A2A] last:border-none">
              <p className="text-4xl sm:text-5xl font-black text-white font-sans uppercase tracking-tight">1.2M+</p>
              <p className="text-[10px] font-mono text-[#666] mt-2 uppercase tracking-[0.2em]">Active Aspirants</p>
            </div>
            <div className="border-r border-[#2A2A2A] last:border-[#2A2A2A] md:last:border-none">
              <p className="text-4xl sm:text-5xl font-black text-white font-sans uppercase tracking-tight">48M+</p>
              <p className="text-[10px] font-mono text-[#666] mt-2 uppercase tracking-[0.2em]">Practice Mocks Taken</p>
            </div>
            <div className="border-r border-[#2A2A2A] last:border-none">
              <p className="text-4xl sm:text-5xl font-black text-white font-sans uppercase tracking-tight">98.4%</p>
              <p className="text-[10px] font-mono text-[#666] mt-2 uppercase tracking-[0.2em]">Accuracy Uplift</p>
            </div>
            <div>
              <p className="text-4xl sm:text-5xl font-black text-white font-sans uppercase tracking-tight">500+</p>
              <p className="text-[10px] font-mono text-[#666] mt-2 uppercase tracking-[0.2em]">Selections This Year</p>
            </div>
          </div>
        </div>
      </section>
 
      {/* Target Exams Selection Grid */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl sm:text-4xl font-sans font-black text-white uppercase tracking-tight mb-4">
            Select Your Exam Stream
          </h2>
          <div className="h-[2px] w-20 bg-[#FF3B3F] mx-auto mb-5" />
          <p className="text-slate-400 text-xs sm:text-sm leading-relaxed max-w-2xl mx-auto">
            Configure your testing environment dynamically. We have aligned direct question pools matching current recruitment standards of central commissions.
          </p>
        </div>
 
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {categories.map((cat, idx) => (
            <div 
              key={cat.id} 
              className="bg-[#1A1A1A] border border-[#2A2A2A] rounded-none p-6 transition-colors duration-200 hover:border-[#FF3B3F]"
            >
              <div className="flex justify-between items-start mb-5">
                <span className="bg-[#0A0A0A] border border-[#2A2A2A] text-white px-3 py-1 rounded-none text-[10px] font-mono tracking-widest uppercase">{cat.id}</span>
                <span className="text-[#FF3B3F] font-mono text-[10px] font-bold uppercase tracking-wider">{cat.difficulty}</span>
              </div>
              <h3 className="text-base font-bold text-white uppercase mb-2">{cat.title}</h3>
              <p className="text-xs text-[#999] mb-6 h-10 overflow-hidden line-clamp-2 leading-relaxed">{cat.desc}</p>
              <div className="pt-4 border-t border-[#2A2A2A]">
                <span className="text-[9px] text-[#666] font-mono uppercase tracking-wider">{cat.stats}</span>
              </div>
            </div>
          ))}
        </div>
      </section>
 
      {/* Dashboard Preview / Bento Features Showcase */}
      <section className="bg-[#1A1A1A] py-24 border-t border-[#2A2A2A]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl sm:text-4xl font-sans font-black text-white uppercase tracking-tight mb-4">
              Pristine Technical Capabilities
            </h2>
            <div className="h-[2px] w-20 bg-[#FF3B3F] mx-auto mb-5" />
            <p className="text-slate-400 text-xs sm:text-sm">
              Precision metrics designed to target and eliminate learning errors on the spot.
            </p>
          </div>
 
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            
            {/* Bento Card 1 */}
            <div className="bg-[#0A0A0A] border border-[#2A2A2A] rounded-none p-8 lg:col-span-2 relative overflow-hidden">
              <div className="p-3 bg-[#1A1A1A] border border-[#2A2A2A] text-white rounded-none w-12 h-12 flex items-center justify-center mb-6">
                <BrainCircuit className="w-5 h-5 text-[#FF3B3F]" />
              </div>
              <h3 className="text-lg font-bold text-white uppercase tracking-tight mb-3">Real-time AI Rank Prediction</h3>
              <p className="text-slate-400 text-xs mb-8 leading-relaxed">
                Our smart profiling script calculates cumulative mock test metrics with peer data, estimating your nationwide All India Rank (AIR) on the spot. Receive instant targets on accuracy percentages needed to bridge selection holes.
              </p>
              <div className="flex items-center gap-3 bg-[#1A1A1A] p-4 border border-[#2A2A2A] rounded-none text-[10px] font-mono uppercase">
                <Activity className="w-4 h-4 text-[#FF3B3F] animate-pulse" />
                <span className="text-[#64748b]">Live Prediction Tracker:</span>
                <span className="text-[#FF3B3F] font-bold ml-auto">AIR #1,250 (91.4% percentile)</span>
              </div>
            </div>
 
            {/* Bento Card 2 */}
            <div className="bg-[#0A0A0A] border border-[#2A2A2A] rounded-none p-8 relative overflow-hidden">
              <div className="p-3 bg-[#1A1A1A] border border-[#2A2A2A] text-white rounded-none w-12 h-12 flex items-center justify-center mb-6">
                <Target className="w-5 h-5 text-[#FF3B3F]" />
              </div>
              <h3 className="text-lg font-bold text-white uppercase tracking-tight mb-3">Subject-Level Accuracy</h3>
              <p className="text-slate-400 text-xs leading-relaxed mb-6">
                Isolate weaknesses. Spot if Quant time overruns, or English grammar accuracy slips. Monitor metrics on subject accuracy mapping.
              </p>
              <ul className="space-y-2.5 text-[10px] font-mono uppercase tracking-wider">
                <li className="flex justify-between items-center bg-[#1A1A1A] border border-[#2A2A2A] px-4 py-2.5 rounded-none">
                  <span className="text-slate-400">Polity & Constitution</span>
                  <span className="text-white font-bold">84% Acc</span>
                </li>
                <li className="flex justify-between items-center bg-[#1A1A1A] border border-[#FF3B3F] px-4 py-2.5 rounded-none">
                  <span className="text-slate-400">Quantitative Aptitude</span>
                  <span className="text-[#FF3B3F] font-bold">51% Acc (Weak Choice)</span>
                </li>
              </ul>
            </div>
 
          </div>
        </div>
      </section>
 
      {/* Active Mock Papers Listing for Practice */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 font-sans">
        <div className="flex flex-col md:flex-row items-start md:items-end justify-between mb-12 gap-4">
          <div>
            <h2 className="text-3xl font-sans font-black text-white uppercase tracking-tight">
              Featured Challenge Papers
            </h2>
            <p className="text-slate-400 text-xs mt-2 font-mono uppercase tracking-wider">
              Select any live standard mock papers. Real time simulation with evaluation.
            </p>
          </div>
          <button 
            onClick={() => {
              if (user) setScreen("dashboard");
              else onOpenAuth();
            }}
            className="flex items-center gap-1.5 text-xs text-[#FF3B3F] font-bold uppercase tracking-wider hover:text-white transition-colors cursor-pointer"
          >
            <span>View all practice pools</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
 
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {DEFAULT_MOCK_TESTS.map((test) => (
            <div 
              key={test.testId}
              className="bg-[#1A1A1A] border border-[#2A2A2A] rounded-none p-6 flex flex-col justify-between hover:border-[#FF3B3F] transition-colors"
            >
              <div>
                <div className="flex items-center justify-between mb-4 text-[10px] font-mono uppercase">
                  <span className="bg-[#0A0A0A] border border-[#2A2A2A] text-[#FF3B3F] px-3 py-1 font-bold tracking-wider">{test.category}</span>
                  <span className="text-[#666] flex items-center gap-1 tracking-wider">
                    <Clock className="w-3.5 h-3.5" />
                    {test.durationMinutes} minutes
                  </span>
                </div>
                <h3 className="text-base font-bold text-white mb-2 leading-snug uppercase tracking-tight">{test.title}</h3>
                <p className="text-xs text-[#666] line-clamp-2 mb-6 leading-relaxed">
                  Practice standard {test.category} test syllabus containing exactly {test.questionsCount} high-yield multiple choice questions. Includes full reviews, timing statistics, and model references.
                </p>
              </div>
 
              <div className="flex items-center justify-between pt-4 border-t border-[#2A2A2A] mt-2">
                <span className="text-[10px] font-mono uppercase text-[#666]">Difficulty: <span className="text-white font-bold">{test.difficulty}</span></span>
                <button
                  onClick={() => handleStartExam(test.testId)}
                  className="px-5 py-2.5 bg-white hover:bg-[#FF3B3F] text-black hover:text-white font-bold text-[10px] uppercase tracking-widest rounded-none transition-all duration-200 flex items-center gap-1.5 shadow-none"
                >
                  <span>Start Mock</span>
                  <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>
 
      {/* Footer Branding Area */}
      <footer className="bg-[#1A1A1A] border-t border-[#2A2A2A] py-16 text-center text-slate-500 text-[10px] font-mono tracking-wider uppercase leading-6">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="mb-4 text-white font-sans font-bold text-xs uppercase tracking-widest">ElitePrep Smart Platform</p>
          <div className="h-[1px] w-24 bg-[#2A2A2A] mx-auto mb-6" />
          <p className="mb-1">Platform ID: <span className="text-white">ab6f9a64-4258-450a-8646-6f98abe02d0f</span></p>
          <p>Protected by Attribute-Based Access Control and Zero-Trust Firestore Security Policies.</p>
          <p className="text-[9px] text-[#444] mt-6 font-mono">&copy; {new Date().getFullYear()} ElitePrep INC. All India Rights Reserved.</p>
        </div>
      </footer>
 
    </div>
  );
}
